repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout
    args: [--drop-empty-cells]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.11.6
  hooks:
  - id: ruff
    args: [--fix]